const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  CLINIC_ADMIN: "CLINIC_ADMIN",
  DOCTOR: "DOCTOR",
  PATIENT: "PATIENT"
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED"
};

const CLINIC_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  SUSPENDED: "SUSPENDED"
};

const APPOINTMENT_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED"
};

const PAYMENT_STATUS = {
  PAID: "PAID",
  UNPAID: "UNPAID"
};

module.exports = {
  ROLES,
  USER_STATUS,
  CLINIC_STATUS,
  APPOINTMENT_STATUS,
  PAYMENT_STATUS
};

